export { HomePage } from './ui/HomePage'
export { CatalogPage } from './ui/CatalogPage'
export { OffersPage } from './ui/OffersPage'
export { ProductPage } from './ui/ProductPage'
export { CatalogProvider, useCatalog } from './model/catalog-store'
export { CATEGORIES, PRODUCTS, getWholesalePrice } from './model/mocks'
export type { Category, Product, ProductPackaging, ProductSpec } from './model/mocks'
