-- Catálogo core: marcas, categorías, unidades, productos, empaques, precios, specs
-- Idempotente con IF NOT EXISTS

CREATE TABLE IF NOT EXISTS brands (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code INT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  sku TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  logo_url TEXT,
  visible BOOLEAN NOT NULL DEFAULT true,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  parent_id UUID REFERENCES categories(id) ON DELETE SET NULL,
  code INT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  sku TEXT UNIQUE,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  icon_key TEXT,
  image_url TEXT,
  visible BOOLEAN NOT NULL DEFAULT true,
  sort_order INT NOT NULL DEFAULT 0,
  show_in_nav BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_categories_parent ON categories(parent_id);

CREATE TABLE IF NOT EXISTS unit_types (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  is_base BOOLEAN NOT NULL DEFAULT false,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code INT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  sku TEXT NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  brand_id UUID REFERENCES brands(id) ON DELETE SET NULL,
  category_id UUID REFERENCES categories(id) ON DELETE SET NULL,
  description TEXT NOT NULL DEFAULT '',
  origin TEXT NOT NULL DEFAULT '',
  moq NUMERIC(18, 4) NOT NULL DEFAULT 1,
  rating NUMERIC(3, 2) NOT NULL DEFAULT 0,
  review_count INT NOT NULL DEFAULT 0,
  featured BOOLEAN NOT NULL DEFAULT false,
  visible BOOLEAN NOT NULL DEFAULT true,
  availability TEXT NOT NULL DEFAULT 'in_stock'
    CHECK (availability IN ('in_stock', 'quote_only', 'out_of_stock')),
  image_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_products_brand ON products(brand_id);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_visible ON products(visible);

CREATE TABLE IF NOT EXISTS product_packagings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  unit_type_id UUID NOT NULL REFERENCES unit_types(id),
  content_qty NUMERIC(18, 4) NOT NULL CHECK (content_qty > 0),
  label TEXT,
  barcode TEXT,
  is_default BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (product_id, unit_type_id, content_qty)
);

CREATE INDEX IF NOT EXISTS idx_packagings_product ON product_packagings(product_id);

CREATE TABLE IF NOT EXISTS product_prices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  packaging_id UUID NOT NULL REFERENCES product_packagings(id) ON DELETE CASCADE,
  price_kind TEXT NOT NULL DEFAULT 'list'
    CHECK (price_kind IN ('list', 'wholesale', 'offer', 'custom')),
  min_qty NUMERIC(18, 4) NOT NULL DEFAULT 1 CHECK (min_qty > 0),
  max_qty NUMERIC(18, 4),
  amount NUMERIC(18, 4) NOT NULL CHECK (amount >= 0),
  compare_at_amount NUMERIC(18, 4),
  currency TEXT NOT NULL DEFAULT 'PEN',
  is_active BOOLEAN NOT NULL DEFAULT true,
  replaces_price_id UUID REFERENCES product_prices(id) ON DELETE SET NULL,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_prices_product_active
  ON product_prices(product_id, is_active, price_kind);

CREATE TABLE IF NOT EXISTS spec_attributes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  key TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  value_type TEXT NOT NULL DEFAULT 'text'
    CHECK (value_type IN ('text', 'number', 'measure')),
  unit_hint TEXT,
  category_id UUID REFERENCES categories(id) ON DELETE SET NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS product_spec_values (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  attribute_id UUID NOT NULL REFERENCES spec_attributes(id) ON DELETE CASCADE,
  value_text TEXT,
  value_number NUMERIC(18, 6),
  unit TEXT,
  sort_order INT NOT NULL DEFAULT 0,
  UNIQUE (product_id, attribute_id)
);

-- Unidades base
INSERT INTO unit_types (code, name, is_base, sort_order)
VALUES
  ('unidad', 'Unidad', true, 1),
  ('paquete', 'Paquete', false, 2),
  ('caja', 'Caja', false, 3)
ON CONFLICT (code) DO NOTHING;

-- Specs frecuentes (medidas con unidad variable)
INSERT INTO spec_attributes (key, name, value_type, unit_hint, sort_order)
VALUES
  ('sku_display', 'SKU', 'text', NULL, 1),
  ('brand_name', 'Marca', 'text', NULL, 2),
  ('origin', 'Origen', 'text', NULL, 3),
  ('moq', 'MOQ', 'number', NULL, 4),
  ('voltage', 'Voltaje', 'measure', 'V', 10),
  ('dimensions', 'Dimensiones', 'measure', 'mm', 11),
  ('weight', 'Peso', 'measure', 'kg', 12),
  ('power', 'Potencia', 'measure', 'W', 13)
ON CONFLICT (key) DO NOTHING;
