-- Combos de ofertas (2x1, pack precio fijo, pack cantidad).
-- Idempotente.

CREATE TABLE IF NOT EXISTS offer_combos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code INT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  sku TEXT NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  image_url TEXT,
  kind TEXT NOT NULL DEFAULT 'bundle_fixed'
    CHECK (kind IN ('bogo', 'bundle_fixed', 'qty_pack')),
  buy_qty INT CHECK (buy_qty IS NULL OR buy_qty >= 1),
  pay_qty INT CHECK (pay_qty IS NULL OR pay_qty >= 1),
  fixed_price NUMERIC(18, 4) CHECK (fixed_price IS NULL OR fixed_price >= 0),
  visible BOOLEAN NOT NULL DEFAULT true,
  valid_from TIMESTAMPTZ,
  valid_to TIMESTAMPTZ,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT offer_combos_bogo_qty CHECK (
    kind <> 'bogo' OR (buy_qty IS NOT NULL AND pay_qty IS NOT NULL AND buy_qty >= pay_qty)
  ),
  CONSTRAINT offer_combos_fixed_price CHECK (
    kind = 'bogo' OR fixed_price IS NOT NULL
  )
);

CREATE INDEX IF NOT EXISTS idx_offer_combos_visible
  ON offer_combos (visible, sort_order, name)
  WHERE visible = true;

CREATE TABLE IF NOT EXISTS offer_combo_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  combo_id UUID NOT NULL REFERENCES offer_combos(id) ON DELETE CASCADE,
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  packaging_id UUID REFERENCES product_packagings(id) ON DELETE SET NULL,
  quantity INT NOT NULL DEFAULT 1 CHECK (quantity >= 1),
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (combo_id, product_id, packaging_id)
);

CREATE INDEX IF NOT EXISTS idx_offer_combo_items_combo
  ON offer_combo_items (combo_id, sort_order);

-- Pedidos / cotizaciones: ítems en JSONB.
-- product: { lineKind:'product', productSlug, productName, presentation, quantity, unitPrice }
-- combo:   { lineKind:'combo', comboId, comboSlug, productName, presentation:'Combo',
--            quantity, unitPrice, comboSnapshot:{ kind, items:[...] } }
